name: Build PHP for Windows

on:
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP version'
        default: '8.3.0'
      extensions:
        description: 'Comma-separated extensions'
        default: 'ftp,mbstring,tokenizer,openssl,curl,zip,pdo,pdo_sqlite,xml,simplexml,dom'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Visual C++ Redistributable
        run: choco install vcredist140 -y
        shell: cmd

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make autoconf automake libtool pkg-config nasm \
                   mingw-w64-x86_64-gcc mingw-w64-x86_64-openssl \
                   mingw-w64-x86_64-libxml2 mingw-w64-x86_64-libzip \
                   mingw-w64-x86_64-libpng mingw-w64-x86_64-libjpeg-turbo \
                   mingw-w64-x86_64-freetype mingw-w64-x86_64-curl \
                   mingw-w64-x86_64-oniguruma mingw-w64-x86_64-libwebp \
                   mingw-w64-x86_64-libssh2 mingw-w64-x86_64-nghttp2 \
                   mingw-w64-x86_64-xz unzip

      - name: Install PHP for MSYS2
        run: |
          curl -L -o /tmp/php.zip https://windows.php.net/downloads/releases/archives/php-${{ github.event.inputs.php_version }}-nts-Win32-vs16-x64.zip
          unzip /tmp/php.zip -d /mingw64
          mkdir -p /mingw64/ext
          mv /mingw64/*.dll /mingw64/ext/ 2>/dev/null || echo "No DLLs found in /mingw64"
          echo "extension=openssl" > /mingw64/php.ini
          echo "extension=ftp" >> /mingw64/php.ini
          echo "extension_dir=/mingw64/ext" >> /mingw64/php.ini
          ln -s /mingw64/php.exe /usr/bin/php
          php --version
          php -m
        shell: msys2 {0}

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/composer.phar -o /usr/local/bin/composer.phar
          chmod +x /usr/local/bin/composer.phar
          echo '#!/usr/bin/env php' | cat - /usr/local/bin/composer.phar > /usr/local/bin/composer
          chmod +x /usr/local/bin/composer
          composer --version
        shell: msys2 {0}

      - name: Download PHP sources
        run: |
          composer config -g secure-http false
          composer install --no-interaction --prefer-dist
          ./bin/spc download --clean
          ./bin/spc download --with-php=${{ github.event.inputs.php_version }} \
                             --for-extensions "${{ github.event.inputs.extensions }}"
        shell: msys2 {0}

      - name: Build PHP
        run: |
          ./bin/spc build --build-cli --build-embed "${{ github.event.inputs.extensions }}"
        shell: msys2 {0}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-windows
          path: bin/php.exe
