name: Build PHP Windows EXE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make autoconf automake libtool pkg-config nasm unzip

      - name: Download PHP 8.3.25 NTS
        run: |
          $phpZip = "$env:TEMP\php.zip"
          Invoke-WebRequest -Uri "https://windows.php.net/downloads/releases/archives/php-8.3.25-nts-Win32-vs16-x64.zip" -OutFile $phpZip
          Expand-Archive -Path $phpZip -DestinationPath "C:\msys64\php"

      - name: Prepare PHP extensions
        run: |
          New-Item -ItemType Directory -Path "C:\msys64\php\ext" -Force
          Move-Item "C:\msys64\php\*.dll" "C:\msys64\php\ext\" -Force
          "extension=openssl" | Out-File "C:\msys64\php\php.ini"
          "extension=ftp" | Out-File "C:\msys64\php\php.ini" -Append
          "extension_dir=C:\msys64\php\ext" | Out-File "C:\msys64\php\php.ini" -Append
          & "C:\msys64\php\php.exe" --version
          & "C:\msys64\php\php.exe" -m

      - name: Checkout static-php-cli
        run: git clone https://github.com/aleksustas89/static-php-cli.git C:\msys64\static-php

      - name: Build PHP exe
        run: |
          cd C:\msys64\static-php
          # пример: сборка CLI с нужными расширениями
          ./bin/spc download --with-php=8.3 --for-extensions "ftp,mbstring,tokenizer,openssl,curl,zip,pdo,pdo_sqlite,xml,simplexml,dom"
          ./bin/spc build --build-cli --build-embed "ftp,mbstring,tokenizer,openssl,curl,zip,pdo,pdo_sqlite,xml,simplexml,dom"

      - name: Upload PHP EXE
        uses: actions/upload-artifact@v4
        with:
          name: php-windows-exe
          path: C:\msys64\static-php\bin\php.exe
