name: Build PHP for Windows

on:
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP version'
        default: '8.3.25'
      extensions:
        description: 'Comma-separated extensions'
        default: 'ftp,mbstring,tokenizer,openssl,curl,zip,pdo,pdo_sqlite,xml,simplexml,dom'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make autoconf automake libtool pkg-config nasm mingw-w64-x86_64-gcc mingw-w64-x86_64-openssl mingw-w64-x86_64-libxml2 mingw-w64-x86_64-libzip mingw-w64-x86_64-libpng mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-freetype mingw-w64-x86_64-curl mingw-w64-x86_64-oniguruma mingw-w64-x86_64-libwebp mingw-w64-x86_64-libssh2 mingw-w64-x86_64-nghttp2 mingw-w64-x86_64-xz unzip

      - name: Download and extract PHP
        shell: pwsh
        run: |
          $phpZip = "$env:TEMP\php.zip"
          Invoke-WebRequest -Uri "https://windows.php.net/downloads/releases/archives/php-8.3.25-nts-Win32-vs16-x64.zip" -OutFile $phpZip
          Expand-Archive -Path $phpZip -DestinationPath "C:\msys64\php" -Force
          Remove-Item $phpZip
          New-Item -ItemType Directory -Path "C:\msys64\php\ext" -Force
          Get-ChildItem "C:\msys64\php" -Filter "*.dll" | Move-Item -Destination "C:\msys64\php\ext" -Force
          Set-Content -Path "C:\msys64\php\php.ini" -Value "extension=openssl`nextension=ftp`nextension_dir=C:\msys64\php\ext"
          "PHP Version:" 
          & "C:\msys64\php\php.exe" -v
          "Extensions:"
          & "C:\msys64\php\php.exe" -m
