name: Build PHP for NativePHP Windows

on:
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP version'
        default: '8.3.0'
      extensions:
        description: 'Comma-separated PHP extensions'
        default: 'ftp,mbstring,tokenizer,openssl,curl,zip,pdo,pdo_sqlite,xml,simplexml,dom'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make autoconf automake libtool pkg-config nasm mingw-w64-x86_64-gcc mingw-w64-x86_64-openssl mingw-w64-x86_64-libxml2 mingw-w64-x86_64-libzip mingw-w64-x86_64-curl unzip

      - name: Download and extract PHP
        run: |
          curl -L -o /tmp/php.zip https://windows.php.net/downloads/releases/archives/php-${{ github.event.inputs.php_version }}-nts-Win32-vs16-x64.zip
          unzip /tmp/php.zip -d /mingw64
          mkdir -p /mingw64/ext
          # Копируем все DLL в папку ext
          mv /mingw64/*.dll /mingw64/ext/ 2>/dev/null || echo "No DLLs to move"
          # Создаем php.ini
          echo "extension_dir=/mingw64/ext" > /mingw64/php.ini
          for ext in $(echo ${{ github.event.inputs.extensions }} | tr "," "\n"); do
            echo "extension=$ext" >> /mingw64/php.ini
          done
          echo "PHP prepared at /mingw64/php.exe"
          /mingw64/php.exe -v
          /mingw64/php.exe -m

      - name: Clone static-php-cli
        run: git clone https://github.com/aleksustas89/static-php-cli.git
      - name: Build static PHP exe
        run: |
          cd static-php-cli
          # Скачиваем исходники PHP для сборки
          ./bin/spc download --with-php=${{ github.event.inputs.php_version }} --for-extensions "${{ github.event.inputs.extensions }}"
          ./bin/spc build --build-cli --build-embed "${{ github.event.inputs.extensions }}"
      - name: Upload PHP exe
        uses: actions/upload-artifact@v4
        with:
          name: nativephp-php
          path: static-php-cli/bin/php.exe
