name: Build PHP for Windows
on:
  workflow_dispatch:
    inputs:
      php_version:
        description: 'PHP version'
        default: '8.3'
      extensions:
        description: 'Comma-separated extensions'
        default: 'ftp,mbstring,tokenizer,openssl,curl,zip,pdo,pdo_sqlite,xml,simplexml,dom'

jobs:
  build:
    runs-on: ubuntu-latest  # ПЕРЕКЛЮЧАЕМСЯ НА LINUX!
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y git curl build-essential autoconf libtool pkg-config nasm
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          chmod +x /usr/local/bin/composer
          
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
        
      - name: Download sources
        run: |
          ./bin/spc download --with-php=${{ github.event.inputs.php_version }} --for-extensions "${{ github.event.inputs.extensions }}"
          
      - name: Build static PHP
        run: |
          ./bin/spc build --build-cli "${{ github.event.inputs.extensions }}"
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-linux
          path: bin/php
